### PR TITLE
fixes variable escaping

### LINKED ISSUE #1099: $$ in ci/cd variables not working as expected
[Use the $ character in CI/CD variables](https://docs.gitlab.com/ee/ci/variables/#use-the--character-in-cicd-variables)

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
$ character in CI/CD variable:
  variables:
    FLAGS: '-al'
    LS_CMD: 'ls "$FLAGS" $$TMP_DIR'
  script:
    - echo "$LS_CMD"  
```

**Expected behavior**
```
'ls -al $TMP_DIR'
```

**Current behavior**
```
'ls -al'
```

### PR DESCRIPTION
**Pull request by ANGkeith**
closes #1099

### CODE REVIEW

File: src/job.ts [hunk 1]
```diff
@@ -395,7 +395,7 @@ export class Job {
         this._startTime = process.hrtime();
         const writeStreams = this.writeStreams;
         const reportsDotenvVariables = await this.initProducerReportsDotenvVariables(writeStreams, Utils.expandVariables(this._variables));
-        const expanded = Utils.expandVariables({...this._variables, ...reportsDotenvVariables});
+        const expanded = Utils.unscape$$Variables(Utils.expandVariables({...this._variables, ...reportsDotenvVariables}));
```
Comment (ANGkeith) [inline src/job.ts:398]: seemed like we're `expandVariables` mutltiple times. 

Thus, moved out the unescape$$ logic to make sure that we don't unescape the `$$` too early.

**Review by firecow — APPROVED** [review]
