### PR TITLE
fix: Boolean false value on inputs breaks configuration syntax

### LINKED ISSUE #1528: Boolean false value on inputs breaks configuration syntax
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
# .gitlab-ci.yml 
include:
  - local: check.yml
    inputs:
      enabled: false
# check.yml 
spec:
  inputs:
    enabled:
      type: boolean
---
check:
  variables:
    IS_ENABLED: $[[ inputs.enabled ]]
  script: echo "enabled value is $IS_ENABLED"
```

**Expected behavior**
gitlab-ci-local should not report error message: 
"This GitLab CI configuration is invalid: `check.yml`: `enabled` input: required value has not been provided."

**Host information**
MacOS 15.3.2, gitlab-ci-local 4.58.0

**Containerd binary**
Brew

**Additional context**
When inputs.enabled=false is set in `.gitlab-ci.yml` file I get error message: 
"This GitLab CI configuration is invalid: `check.yml`: `enabled` input: required value has not been provided."
When inputs.enabled=true is set in `.gitlab-ci.yml`, everything works as expected.

### PR DESCRIPTION
**Pull request by ANGkeith**
closes #1528

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -409,7 +409,8 @@ function parseIncludeInputs (ctx: any): {inputValue: any; inputType: InputType}
 
 function getInputValue (ctx: any) {
     const {inputs, interpolationKey, configFilePath, inputsSpecification} = ctx;
-    const inputValue = inputs[interpolationKey] || inputsSpecification.spec.inputs[interpolationKey]?.default;
+    const inputValue = inputs[interpolationKey]
+      ?? inputsSpecification.spec.inputs[interpolationKey]?.default;
```
Comment (firecow) [inline src/parser.ts:413]:
```suggestion
    const inputValue = inputs[interpolationKey] ?? inputsSpecification.spec.inputs[interpolationKey]?.default;
```

File: tests/test-cases/include-inputs/integration.test.ts [hunk 2]
```diff
@@ -244,6 +245,27 @@ scan-website:
...
+stages:
+  - .pre
+  - test
+  - .post
+scan-website:
+  script:
+    - echo false`;
+
+    expect(writeStreams.stdoutLines[0]).toEqual(expected);
+});
```
Comment (firecow) [inline tests/test-cases/include-inputs/integration.test.ts:267]:
```suggestion
    const expected = [
        "---",
        "stages:",
        "  - .pre",
        "  - test",
        "  - .post",
        "scan-website:",
        "  script:",
        "    - echo false",
    ];

    expect(writeStreams.stdoutLines[0]).toEqual(expected.join("\n"));
});
```

**Review by firecow — APPROVED** [review]

File: tests/test-cases/include-inputs/integration.test.ts (hunk 2 above)
Comment (ANGkeith) [reply tests/test-cases/include-inputs/integration.test.ts:267]: do you still want me to apply the suggestion ? i see that you've approve the pr

personally i prefer the backticks version because for ease of (typing/copy pasting)...

File: src/parser.ts (hunk 1 above)
Comment (ANGkeith) [reply src/parser.ts:413]: i see you prefer this syntax, 

so added https://github.com/firecow/gitlab-ci-local/pull/1532/commits/116267b4123c7ce48cd6c4084a4d64251e707d45 

to enforce it

Comment (firecow) [reply src/parser.ts]: I :heart: you :smile:

File: tests/test-cases/include-inputs/integration.test.ts (hunk 2 above)
Comment (firecow) [reply tests/test-cases/include-inputs/integration.test.ts:267]: I don't prefer the weird indentation or backticks, but I can live with both :smile:
