### PR TITLE
Fix bug in job-expanders jobExtends function

### LINKED ISSUE #484: YAML Script anchor does not work if it's not a list
**Minimal .gitlab-ci.yml illustrating the issue**

Same example as #24 

```yml
---
.example: &test_anchor
  echo 'Example'
demo:
  stage: test
  script:
    - echo 'Hello'
    - *test_anchor
```

I got:
```
TypeError: Cannot create property 'extends' on string 'echo 'Example''
    at Object.jobExtends (/usr/lib/node_modules/gitlab-ci-local/src/job-expanders.ts:25:24)
    at Parser.init (/usr/lib/node_modules/gitlab-ci-local/src/parser.ts:84:22)
    at Function.create (/usr/lib/node_modules/gitlab-ci-local/src/parser.ts:54:9)
    at handler (/usr/lib/node_modules/gitlab-ci-local/src/handler.ts:115:18)
    at Object.handler (/usr/lib/node_modules/gitlab-ci-local/src/index.ts:25:34)
```

**Expected behavior**
It should work exactly as:
```yml
---
demo:
  stage: test
  script:
    - echo 'Hello'
    - echo 'Example'
```
as it's YAML equivalent

**Host information**
Ubuntu
gitlab-ci-local 4.31.0

**Additional context**
this issue is easy to workaround by using an array:
```yaml
.example: &test_anchor
  - echo 'Example'
```

but it is really an issue when including external pipeline code such [to-be-continuous templates](https://gitlab.com/to-be-continuous)

### PR DESCRIPTION
**Pull request by firecow**
closes #484

### CODE REVIEW

File: src/job-expanders.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ const extendsRecurse = (gitlabData: any, jobName: string, jobData: any, parents:
 export function jobExtends(gitlabData: any) {
     for (const [jobName, jobData] of Object.entries<any>(gitlabData)) {
         if (Job.illegalJobNames.includes(jobName)) continue;
+        if (typeof jobData != "object") continue;
```
Comment (LauJosefsen) [inline src/job-expanders.ts:25]: What can the type then be?

**Review by LauJosefsen — APPROVED** [review]

File: src/job-expanders.ts (hunk 1 above)
Comment (firecow) [reply src/job-expanders.ts:25]: string, boolean, number see issue https://github.com/firecow/gitlab-ci-local/issues/484
