### PR TITLE
fix: error when using include:component pipeline with ssh protocol 

### LINKED ISSUE #1238: 4.49.0 breaks ssh git remote ?
```
$ git remote get-url origin
ssh://git@xxxxxxxxxxxxxxxxxxxxxx.git

----------------------------------------------------------------------------------------------------------------------
$ gitlab-ci-local --version
4.49.0

----------------------------------------------------------------------------------------------------------------------
$ gitlab-ci-local
Error: ssh not supported!
    at Function.remoteFileExist (/snapshot/firecow-gitlab-ci-local/src/utils.ts:285:23)
    at Function.init (/snapshot/firecow-gitlab-ci-local/src/parser-includes.ts:113:39)
    at Parser.init (/snapshot/firecow-gitlab-ci-local/src/parser.ts:95:44)
    at Function.create (/snapshot/firecow-gitlab-ci-local/src/parser.ts:59:9)
    at handler (/snapshot/firecow-gitlab-ci-local/src/handler.ts:77:18)
    at Object.handler (/snapshot/firecow-gitlab-ci-local/src/index.ts:36:21)
  
----------------------------------------------------------------------------------------------------------------------
$ apt-cache policy gitlab-ci-local
gitlab-ci-local:
  Installé : 4.49.0
  Candidat : 4.49.0
 Table de version :
 *** 4.49.0 500
        500 https://gitlab-ci-local-ppa.firecow.dk ./ Packages
        100 /var/lib/dpkg/status
     4.48.2 500
        500 https://gitlab-ci-local-ppa.firecow.dk ./ Packages
        ...

----------------------------------------------------------------------------------------------------------------------
$ sudo apt install gitlab-ci-local=4.48.2
Dépaquetage de gitlab-ci-local (4.48.2) sur (4.49.0) ...
Paramétrage de gitlab-ci-local (4.48.2) ...

----------------------------------------------------------------------------------------------------------------------
$ gitlab-ci-local 
parsing and downloads finished in 2.15 s
```

OS ubuntu 24.04
No need to tell more than that I think ?
By the way, thank you mainteners and contributors for this project !

### PR DESCRIPTION
**Pull request by ANGkeith**
closes #1238

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -285,6 +285,7 @@ export class Utils {
 
     static async remoteFileExist (file: string, ref: string, domain: string, projectPath: string, protocol: string) {
         switch (protocol) {
+            case "ssh":
             case "git":
                 try {
                     await Utils.bash(`git archive --remote=ssh://git@${domain}/${projectPath}.git ${ref} ${file} > /dev/null`);
```
Comment (ANGkeith) [inline src/utils.ts:291]: for gitlab that's hosted on non standard ssh port this will probably fail but that's for another time XD

**Review by firecow — APPROVED** [review]
