### PR TITLE
early return from rules evaluation after first match

### LINKED ISSUE #1252: Rules evaluation is incorrect and it doesn't stop after the first match
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
variables:
  VAR1: val1
  VAR2: val2

Test:
  script:
    - echo "hello"
  rules:
    - if: $VAR1 == 'val1'
    - if: $VAR2 == 'val2'
      when: never
```

Running `gitlab-ci-local --list` with the above gitlab ci configuration produces incorrect results (it doesn't list the Test job)
```
parsing and downloads finished in 63 ms
json schema validated in 95 ms
name  description  stage   when   allow_failure  needs
```

**Expected behavior**
`gitlab-ci-local --list` should list the "Test" job as the first rule evaluates to true.

**Host information**
Mac 14.4.1
gitlab-ci-local 4.50.0 and above

**Additional context**
This started happening with version 4.50.0. Possibly due to https://github.com/firecow/gitlab-ci-local/commit/ef8097bedca05230bef15a3f52d395a6414eef23 as it doesn't stop evaluating rules unless when = never

But [Gitlab docs for rules](https://docs.gitlab.com/ee/ci/yaml/#rules) says

> Rules are evaluated when the pipeline is created, and evaluated in order until the first match

### PR DESCRIPTION
**Pull request by vivek9ru3**
fixes #1252

### CODE REVIEW

**Review by ANGkeith — APPROVED** [review]

File: src/utils.ts [hunk 1]
```diff
@@ -196,7 +196,7 @@ export class Utils {
             allowFailure = rule.allow_failure ?? allowFailure;
             ruleVariable = rule.variables;
 
-            if (when === "never") break; // Early return, will not evaluate the remaining rules
+            break; // Early return, will not evaluate the remaining rules
```
Comment (ANGkeith) [inline src/utils.ts:199]:
```suggestion
            break; // Rules are evaluated in order until the first match
```

**Comment by ANGkeith** [comment]
LGTM! thanks for the fix

**Comment by ANGkeith** [comment]
fixes #1252
